name: absensiapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Cupertino Icons
  dotted_border: ^2.1.0 # Dotted Border
  camera: ^0.11.0+2 # Camera
  geolocator: ^13.0.2 # Geolocation
  geocoding: ^3.0.0  # Geocoding
  intl: ^0.20.1 # Internationalization Library untuk format tanggal, waktu, dan angka dalam berbagai bahasa.
  lottie: ^3.1.3 # Lottie Animation
  google_mlkit_face_detection: ^0.12.0 # Face Detection
  cloud_firestore: ^5.6.3 # Connect Cloud Firestore (firebase database)
  firebase_core: ^3.11.0 # Connect Flutter to Firebase
  firebase_auth: ^5.4.2 # Firebase Authentication
  image_picker: ^1.1.2 # mage Picker
  file_picker: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/raw/

